require("heatshrink").decompress(
  atob(
    "mEwwcBkmSpIC/AVdt2/btu+AQP27dv23bCIlLCJdkCIdbCJdsCP4RLv//AAX2AgYAC/gjIDoI1P22bCJ+wjYR/Pouwj6AFPpIjC+mbGpKMCCIXwjYRJ2gRB0EDCJggCwARTAoIRQiZ9JPQWEw//wEHQAR9GEAWG4YFCt4sBGowRFwmDCJIOCg3CAoVvDQIRGBwNsg3ACIIUBCI1AgAOBARIRVfYgAHPogRRLIO3dIO+AQP27bFJCOdLCJdkCIdJCJYOCAX4CrA==",
  ),
);
